extends RefCounted

var current_locale := "es"

const LOCALES := [
	{"code": "en", "label": "English"},
	{"code": "es", "label": "Español"},
	{"code": "ja", "label": "日本語"},
]

const TRANSLATIONS := {
	"en": {
		"game.title": "HoloOffice",
		"hud.money": "Funds: ${amount}",
		"hud.day": "Day {day}",
		"hud.level": "Level {level}",
		"hud.reputation": "Reputation: {value}",
		"hud.staff": "Workers: {count}",
		"hud.talents": "Talents: {count}",
		"hud.payroll": "Monthly payroll: ${amount}",
		"hud.time": "Time: {time} ({speed})",
		"hud.selected.none": "Selected: none",
		"hud.selected.worker": "Selected worker: {name} ({role})",
		"hud.selected.talent": "Selected talent: {name} [{task}]",
		"hud.room_summary": "Rooms: Office {office} / Bathroom {bathroom} / Storage {storage}",
		"hud.worker_offer": "{name} | Ops {ops} | Mood {mood} | Salary ${salary}",
		"hud.talent_offer": "{name} | {focus} | Contract ${salary} | Unlock Lv {level}",
		"hud.instructions": "Left click to build or designate. Click a character to select them. Right click cancels the current build mode.",
		"panel.build": "Construction",
		"panel.staff": "Recruitment",
		"panel.assignment": "Talent Assignment",
		"panel.logs": "Daily Log",
		"panel.language": "Language",
		"button.pause": "Pause",
		"button.resume": "Resume",
		"button.speed": "Speed x{value}",
		"button.mode.wall": "Wall",
		"button.mode.door": "Door",
		"button.mode.floor": "Floor",
		"button.mode.erase": "Erase",
		"button.mode.office": "Office",
		"button.mode.bathroom": "Bathroom",
		"button.mode.storage": "Storage",
		"button.hire_worker": "Hire Worker",
		"button.hire_talent": "Hire Talent",
		"button.task.stream": "Assign to Streaming",
		"button.task.concert": "Assign to Concerts",
		"button.task.merch": "Assign to Merch",
		"button.task.idle": "Set Idle",
		"mode.none": "Selection",
		"mode.wall": "Placing walls",
		"mode.door": "Placing doors",
		"mode.floor": "Placing floors",
		"mode.erase": "Removing tiles",
		"mode.designate_office": "Designating office",
		"mode.designate_bathroom": "Designating bathroom",
		"mode.designate_storage": "Designating storage",
		"task.idle": "Idle",
		"task.stream": "Streaming",
		"task.concert": "Concerts",
		"task.merch": "Merch",
		"designation.office": "Office",
		"designation.bathroom": "Bathroom",
		"designation.storage": "Storage",
		"role.producer": "Producer",
		"role.hr": "HR",
		"role.builder": "Builder",
		"role.logistics": "Logistics",
		"focus.streaming": "Streaming specialist",
		"focus.performance": "Performance ace",
		"focus.merch": "Merch ambassador",
		"log.start": "HoloOffice headquarters is open for business.",
		"log.build": "{name} added at ({x}, {y}).",
		"log.designate": "{designation} assigned at ({x}, {y}).",
		"log.erase": "Tile cleared at ({x}, {y}).",
		"log.worker_hired": "Worker hired: {name}.",
		"log.talent_hired": "Talent signed: {name}.",
		"log.task_assigned": "{name} is now focused on {task}.",
		"log.new_day": "Day {day} revenue: ${amount}.",
		"log.payroll": "Monthly payroll paid: ${amount}.",
		"log.level_up": "Company level increased to {level}.",
		"log.locked_talent": "{name} unlocks at company level {level}.",
		"log.not_enough_money": "Not enough funds.",
		"log.no_selection": "Select a talent first.",
		"log.cancel_mode": "Build mode cancelled.",
	},
	"es": {
		"game.title": "HoloOffice",
		"hud.money": "Fondos: ${amount}",
		"hud.day": "Día {day}",
		"hud.level": "Nivel {level}",
		"hud.reputation": "Reputación: {value}",
		"hud.staff": "Empleados: {count}",
		"hud.talents": "Talentos: {count}",
		"hud.payroll": "Nómina mensual: ${amount}",
		"hud.time": "Tiempo: {time} ({speed})",
		"hud.selected.none": "Seleccionado: nadie",
		"hud.selected.worker": "Empleado seleccionado: {name} ({role})",
		"hud.selected.talent": "Talento seleccionado: {name} [{task}]",
		"hud.room_summary": "Salas: Oficina {office} / Baño {bathroom} / Almacén {storage}",
		"hud.worker_offer": "{name} | Ops {ops} | Ánimo {mood} | Sueldo ${salary}",
		"hud.talent_offer": "{name} | {focus} | Contrato ${salary} | Desbloqueo Nv {level}",
		"hud.instructions": "Clic izquierdo para construir o designar. Haz clic en un personaje para seleccionarlo. Clic derecho cancela el modo actual.",
		"panel.build": "Construcción",
		"panel.staff": "Reclutamiento",
		"panel.assignment": "Asignación de Talentos",
		"panel.logs": "Registro Diario",
		"panel.language": "Idioma",
		"button.pause": "Pausar",
		"button.resume": "Reanudar",
		"button.speed": "Velocidad x{value}",
		"button.mode.wall": "Muro",
		"button.mode.door": "Puerta",
		"button.mode.floor": "Suelo",
		"button.mode.erase": "Borrar",
		"button.mode.office": "Oficina",
		"button.mode.bathroom": "Baño",
		"button.mode.storage": "Almacén",
		"button.hire_worker": "Contratar Empleado",
		"button.hire_talent": "Contratar Talento",
		"button.task.stream": "Asignar a Streaming",
		"button.task.concert": "Asignar a Conciertos",
		"button.task.merch": "Asignar a Merch",
		"button.task.idle": "Dejar en Espera",
		"mode.none": "Selección",
		"mode.wall": "Colocando muros",
		"mode.door": "Colocando puertas",
		"mode.floor": "Colocando suelo",
		"mode.erase": "Quitando casillas",
		"mode.designate_office": "Designando oficina",
		"mode.designate_bathroom": "Designando baño",
		"mode.designate_storage": "Designando almacén",
		"task.idle": "En espera",
		"task.stream": "Streaming",
		"task.concert": "Conciertos",
		"task.merch": "Merch",
		"designation.office": "Oficina",
		"designation.bathroom": "Baño",
		"designation.storage": "Almacén",
		"role.producer": "Productor",
		"role.hr": "RR. HH.",
		"role.builder": "Constructor",
		"role.logistics": "Logística",
		"focus.streaming": "Especialista en streaming",
		"focus.performance": "As del escenario",
		"focus.merch": "Embajadora de merch",
		"log.start": "La sede de HoloOffice abrió sus puertas.",
		"log.build": "{name} agregado en ({x}, {y}).",
		"log.designate": "{designation} asignado en ({x}, {y}).",
		"log.erase": "Casilla limpiada en ({x}, {y}).",
		"log.worker_hired": "Empleado contratado: {name}.",
		"log.talent_hired": "Talento fichado: {name}.",
		"log.task_assigned": "{name} ahora se enfoca en {task}.",
		"log.new_day": "Ingresos del día {day}: ${amount}.",
		"log.payroll": "Nómina mensual pagada: ${amount}.",
		"log.level_up": "La empresa subió al nivel {level}.",
		"log.locked_talent": "{name} se desbloquea en nivel de empresa {level}.",
		"log.not_enough_money": "No hay fondos suficientes.",
		"log.no_selection": "Primero selecciona un talento.",
		"log.cancel_mode": "Modo de construcción cancelado.",
	},
	"ja": {
		"game.title": "HoloOffice",
		"hud.money": "資金: ${amount}",
		"hud.day": "{day}日目",
		"hud.level": "レベル {level}",
		"hud.reputation": "評判: {value}",
		"hud.staff": "社員: {count}",
		"hud.talents": "タレント: {count}",
		"hud.payroll": "月給合計: ${amount}",
		"hud.time": "時間: {time} ({speed})",
		"hud.selected.none": "選択中: なし",
		"hud.selected.worker": "選択中の社員: {name} ({role})",
		"hud.selected.talent": "選択中のタレント: {name} [{task}]",
		"hud.room_summary": "部屋: オフィス {office} / バスルーム {bathroom} / 倉庫 {storage}",
		"hud.worker_offer": "{name} | 業務 {ops} | 気分 {mood} | 給与 ${salary}",
		"hud.talent_offer": "{name} | {focus} | 契約 ${salary} | 開放 Lv {level}",
		"hud.instructions": "左クリックで建築または指定。キャラクターをクリックすると選択。右クリックで現在のモードを解除します。",
		"panel.build": "建築",
		"panel.staff": "採用",
		"panel.assignment": "タレント配置",
		"panel.logs": "日報",
		"panel.language": "言語",
		"button.pause": "一時停止",
		"button.resume": "再開",
		"button.speed": "速度 x{value}",
		"button.mode.wall": "壁",
		"button.mode.door": "ドア",
		"button.mode.floor": "床",
		"button.mode.erase": "削除",
		"button.mode.office": "オフィス",
		"button.mode.bathroom": "バスルーム",
		"button.mode.storage": "倉庫",
		"button.hire_worker": "社員を雇う",
		"button.hire_talent": "タレントを雇う",
		"button.task.stream": "配信に配置",
		"button.task.concert": "ライブに配置",
		"button.task.merch": "グッズに配置",
		"button.task.idle": "待機にする",
		"mode.none": "選択",
		"mode.wall": "壁を配置中",
		"mode.door": "ドアを配置中",
		"mode.floor": "床を配置中",
		"mode.erase": "タイルを削除中",
		"mode.designate_office": "オフィス指定中",
		"mode.designate_bathroom": "バスルーム指定中",
		"mode.designate_storage": "倉庫指定中",
		"task.idle": "待機",
		"task.stream": "配信",
		"task.concert": "ライブ",
		"task.merch": "グッズ",
		"designation.office": "オフィス",
		"designation.bathroom": "バスルーム",
		"designation.storage": "倉庫",
		"role.producer": "プロデューサー",
		"role.hr": "人事",
		"role.builder": "建設担当",
		"role.logistics": "物流",
		"focus.streaming": "配信スペシャリスト",
		"focus.performance": "ステージエース",
		"focus.merch": "グッズ大使",
		"log.start": "HoloOffice本社の営業を開始しました。",
		"log.build": "{name} を ({x}, {y}) に配置しました。",
		"log.designate": "{designation} を ({x}, {y}) に指定しました。",
		"log.erase": "({x}, {y}) のタイルを消去しました。",
		"log.worker_hired": "{name} を社員として採用しました。",
		"log.talent_hired": "{name} と契約しました。",
		"log.task_assigned": "{name} を {task} に集中させます。",
		"log.new_day": "{day}日目の収益: ${amount}",
		"log.payroll": "月給を支払いました: ${amount}",
		"log.level_up": "会社レベルが {level} になりました。",
		"log.locked_talent": "{name} は会社レベル {level} で開放されます。",
		"log.not_enough_money": "資金が足りません。",
		"log.no_selection": "先にタレントを選択してください。",
		"log.cancel_mode": "建築モードを解除しました。",
	},
}


func set_locale(locale_code: String) -> void:
	if TRANSLATIONS.has(locale_code):
		current_locale = locale_code


func tr(key: String, replacements: Dictionary = {}) -> String:
	var locale_table: Dictionary = TRANSLATIONS.get(current_locale, TRANSLATIONS["en"])
	var template: String = locale_table.get(key, TRANSLATIONS["en"].get(key, key))
	for replacement_key in replacements.keys():
		template = template.replace("{%s}" % replacement_key, str(replacements[replacement_key]))
	return template
