extends RefCounted
class_name HoloLocalization

var current_locale: String = "es"

const LOCALES: Array[Dictionary] = [
	{"code": "en", "label": "English"},
	{"code": "es", "label": "Espanol"},
	{"code": "ja", "label": "Nihongo"},
]

const TRANSLATIONS := {
	"en": {
		"game.title": "HoloOffice",
		"hud.money": "Funds: ${amount}",
		"hud.day": "Day {day}",
		"hud.level": "Level {level}",
		"hud.reputation": "Reputation: {value}",
		"hud.staff": "Workers: {count}",
		"hud.talents": "Talents: {count}",
		"hud.payroll": "Monthly payroll: ${amount}",
		"hud.time": "Time: {time} ({speed})",
		"hud.selected.none": "Selected: none",
		"hud.selected.worker": "Selected worker: {name} ({role})",
		"hud.selected.talent": "Selected talent: {name} [{task}]",
		"hud.room_summary": "Rooms: Office {office} / Bathroom {bathroom} / Storage {storage} / Shop {shop} / Booth {recording_booth}",
		"hud.worker_assignment": "Assigned chair: {value}",
		"panel.areas": "Areas",
		"panel.structures": "Structures",
		"panel.furniture": "Furniture",
		"menu.research": "Research Tree",
		"menu.recruit": "Hire Workers",
		"menu.recruit.title": "Recruit Workers",
		"menu.talent": "Sign Talent",
		"menu.finance": "Finances",
		"button.close": "Close",
		"button.research.start": "Start Research",
		"button.recruit.researcher": "Researcher",
		"button.recruit.janitor": "Janitor",
		"button.recruit.builder": "Constructor",
		"button.recruit.staff": "Staff",
		"button.recruit.cashier": "Cashier",
		"button.mode.wall": "Wall",
		"button.mode.door": "Door",
		"button.mode.floor": "Floor",
		"button.mode.erase": "Erase",
		"button.mode.office": "Office",
		"button.mode.bathroom": "Bathroom",
		"button.mode.storage": "Storage",
		"button.mode.shop": "Shop",
		"button.mode.recording_booth": "Recording Booth",
		"button.mode.clear_area": "Clear Area",
		"button.mode.chair": "Chair",
		"button.mode.table": "Table",
		"button.mode.wall_pad": "Wall Pad",
		"button.mode.shelf": "Shelf",
		"button.mode.droppoint": "Drop Point",
		"button.mode.checkout": "Checkout",
		"button.talent.assign_booth": "Work here",
		"button.talent.unassign_booth": "Stop working here",
		"button.shop.link_storage": "Link with storage",
		"button.shop.unlink_storage": "Unlink storage",
		"mode.none": "Selection",
		"mode.wall": "Placing walls",
		"mode.door": "Placing doors",
		"mode.floor": "Placing floors",
		"mode.erase": "Removing tiles",
		"mode.designate_office": "Designating office",
		"mode.designate_bathroom": "Designating bathroom",
		"mode.designate_storage": "Designating storage",
		"mode.designate_shop": "Designating shop",
		"mode.designate_recording_booth": "Designating recording booth",
		"mode.clear_area": "Clearing area designation",
		"mode.chair": "Placing chair",
		"mode.table": "Placing table",
		"mode.wall_pad": "Placing wall pad",
		"mode.shelf": "Placing shelf",
		"mode.droppoint": "Placing drop point",
		"mode.checkout": "Placing checkout",
		"designation.office": "Office",
		"designation.bathroom": "Bathroom",
		"designation.storage": "Storage",
		"designation.shop": "Shop",
		"designation.recording_booth": "Recording Booth",
		"role.researcher": "Researcher",
		"role.janitor": "Janitor",
		"role.builder": "Constructor",
		"role.staff": "Staff",
		"role.cashier": "Cashier",
		"role.talent": "Talent",
		"stat.research": "Research",
		"stat.build": "Build",
		"stat.clean": "Clean",
		"recruit.info": "Choose a role, then pick one of three candidates.",
		"recruit.candidate": "{name} | {role} | Res {research} | Build {build} | Clean {clean} | Salary ${salary}",
		"talent.info": "Pick one of three talents, then select one and right click a recording booth.",
		"finance.today_income": "Today income",
		"finance.today_expenses": "Today expenses",
		"finance.today_net": "Today net",
		"finance.month_income": "Month income",
		"finance.month_expenses": "Month expenses",
		"finance.month_net": "Month net",
		"finance.lifetime_income": "Lifetime income",
		"finance.lifetime_expenses": "Lifetime expenses",
		"finance.lifetime_net": "Lifetime net",
		"finance.recording_income": "Recording studio income",
		"finance.shop_sales": "Shop sales income",
		"finance.last_payroll": "Last payroll",
		"finance.monthly_payroll_due": "Monthly payroll due",
		"finance.active_talents": "Active talents",
		"blueprint.wall": "Wall blueprint",
		"blueprint.floor": "Floor blueprint",
		"blueprint.door": "Door blueprint",
		"blueprint.chair": "Chair blueprint",
		"blueprint.table": "Table blueprint",
		"blueprint.wall_pad": "Wall pad blueprint",
		"blueprint.shelf": "Shelf blueprint",
		"blueprint.droppoint": "Drop point blueprint",
		"blueprint.checkout": "Checkout blueprint",
		"research.none": "No active research",
		"research.chairs.name": "Basic Seating",
		"research.chairs.desc": "Unlock office chairs. Assigned chairs boost one worker's research output by 10%.",
		"research.completed": "Completed",
		"log.blueprint_created": "{name} planned at ({x}, {y}).",
		"log.invalid_designation_room": "Area must be inside an enclosed room.",
	},
	"es": {
		"game.title": "HoloOffice",
		"hud.money": "Fondos: ${amount}",
		"hud.day": "Dia {day}",
		"hud.level": "Nivel {level}",
		"hud.reputation": "Reputacion: {value}",
		"hud.staff": "Empleados: {count}",
		"hud.talents": "Talentos: {count}",
		"hud.payroll": "Nomina mensual: ${amount}",
		"hud.time": "Tiempo: {time} ({speed})",
		"hud.selected.none": "Seleccionado: nadie",
		"hud.selected.worker": "Empleado seleccionado: {name} ({role})",
		"hud.selected.talent": "Talento seleccionado: {name} [{task}]",
		"hud.room_summary": "Salas: Oficina {office} / Bano {bathroom} / Almacen {storage} / Tienda {shop} / Cabina {recording_booth}",
		"hud.worker_assignment": "Silla asignada: {value}",
		"panel.areas": "Areas",
		"panel.structures": "Estructuras",
		"panel.furniture": "Muebles",
		"menu.research": "Arbol de investigacion",
		"menu.recruit": "Contratar empleados",
		"menu.recruit.title": "Contratar empleados",
		"menu.talent": "Contratar talento",
		"menu.finance": "Finanzas",
		"button.close": "Cerrar",
		"button.research.start": "Iniciar investigacion",
		"button.recruit.researcher": "Investigador",
		"button.recruit.janitor": "Conserje",
		"button.recruit.builder": "Constructor",
		"button.recruit.staff": "Staff",
		"button.recruit.cashier": "Cajero",
		"button.mode.wall": "Muro",
		"button.mode.door": "Puerta",
		"button.mode.floor": "Suelo",
		"button.mode.erase": "Borrar",
		"button.mode.office": "Oficina",
		"button.mode.bathroom": "Bano",
		"button.mode.storage": "Almacen",
		"button.mode.shop": "Tienda",
		"button.mode.recording_booth": "Cabina",
		"button.mode.clear_area": "Limpiar area",
		"button.mode.chair": "Silla",
		"button.mode.table": "Mesa",
		"button.mode.wall_pad": "Panel",
		"button.mode.shelf": "Estante",
		"button.mode.droppoint": "Punto de entrega",
		"button.mode.checkout": "Caja",
		"button.talent.assign_booth": "Trabajar aqui",
		"button.talent.unassign_booth": "Dejar de trabajar aqui",
		"button.shop.link_storage": "Vincular con almacen",
		"button.shop.unlink_storage": "Desvincular almacen",
		"mode.none": "Seleccion",
		"mode.wall": "Colocando muros",
		"mode.door": "Colocando puertas",
		"mode.floor": "Colocando suelo",
		"mode.erase": "Quitando casillas",
		"mode.designate_office": "Designando oficina",
		"mode.designate_bathroom": "Designando bano",
		"mode.designate_storage": "Designando almacen",
		"mode.designate_shop": "Designando tienda",
		"mode.designate_recording_booth": "Designando cabina",
		"mode.clear_area": "Limpiando designacion",
		"mode.chair": "Colocando silla",
		"mode.table": "Colocando mesa",
		"mode.wall_pad": "Colocando panel",
		"mode.shelf": "Colocando estante",
		"mode.droppoint": "Colocando punto de entrega",
		"mode.checkout": "Colocando caja",
		"designation.office": "Oficina",
		"designation.bathroom": "Bano",
		"designation.storage": "Almacen",
		"designation.shop": "Tienda",
		"designation.recording_booth": "Cabina",
		"role.researcher": "Investigador",
		"role.janitor": "Conserje",
		"role.builder": "Constructor",
		"role.staff": "Staff",
		"role.cashier": "Cajero",
		"role.talent": "Talento",
		"stat.research": "Investigacion",
		"stat.build": "Construccion",
		"stat.clean": "Limpieza",
		"recruit.info": "Elige un rol y luego selecciona uno de tres candidatos.",
		"recruit.candidate": "{name} | {role} | Inv {research} | Cons {build} | Limp {clean} | Sueldo ${salary}",
		"talent.info": "Elige uno de tres talentos y luego usa clic derecho sobre una cabina.",
		"finance.today_income": "Ingresos de hoy",
		"finance.today_expenses": "Gastos de hoy",
		"finance.today_net": "Neto de hoy",
		"finance.month_income": "Ingresos del mes",
		"finance.month_expenses": "Gastos del mes",
		"finance.month_net": "Neto del mes",
		"finance.lifetime_income": "Ingresos totales",
		"finance.lifetime_expenses": "Gastos totales",
		"finance.lifetime_net": "Neto total",
		"finance.recording_income": "Ingresos de recording",
		"finance.shop_sales": "Ingresos de tienda",
		"finance.last_payroll": "Ultima nomina",
		"finance.monthly_payroll_due": "Nomina mensual",
		"finance.active_talents": "Talentos activos",
		"blueprint.wall": "Plano de muro",
		"blueprint.floor": "Plano de suelo",
		"blueprint.door": "Plano de puerta",
		"blueprint.chair": "Plano de silla",
		"blueprint.table": "Plano de mesa",
		"blueprint.wall_pad": "Plano de panel",
		"blueprint.shelf": "Plano de estante",
		"blueprint.droppoint": "Plano de punto de entrega",
		"blueprint.checkout": "Plano de caja",
		"research.none": "Sin investigacion activa",
		"research.chairs.name": "Asientos basicos",
		"research.chairs.desc": "Desbloquea sillas de oficina. Cada silla asignada mejora en 10% la investigacion de un empleado.",
		"research.completed": "Completado",
		"log.blueprint_created": "{name} planificado en ({x}, {y}).",
		"log.invalid_designation_room": "El area debe estar dentro de una habitacion cerrada.",
	},
	"ja": {
		"game.title": "HoloOffice",
		"hud.money": "Funds: ${amount}",
		"hud.day": "Day {day}",
		"hud.level": "Level {level}",
		"hud.reputation": "Reputation: {value}",
		"hud.staff": "Workers: {count}",
		"hud.talents": "Talents: {count}",
		"hud.payroll": "Monthly payroll: ${amount}",
		"hud.time": "Time: {time} ({speed})",
		"hud.selected.none": "Selected: none",
		"hud.selected.worker": "Selected worker: {name} ({role})",
		"hud.selected.talent": "Selected talent: {name} [{task}]",
		"hud.room_summary": "Rooms: Office {office} / Bathroom {bathroom} / Storage {storage} / Shop {shop} / Booth {recording_booth}",
		"hud.worker_assignment": "Assigned chair: {value}",
		"panel.areas": "Areas",
		"panel.structures": "Structures",
		"panel.furniture": "Furniture",
		"menu.research": "Research Tree",
		"menu.recruit": "Hire Workers",
		"menu.recruit.title": "Recruit Workers",
		"menu.talent": "Sign Talent",
		"menu.finance": "Finances",
		"button.close": "Close",
		"button.research.start": "Start Research",
		"button.recruit.researcher": "Researcher",
		"button.recruit.janitor": "Janitor",
		"button.recruit.builder": "Constructor",
		"button.recruit.staff": "Staff",
		"button.recruit.cashier": "Cashier",
		"button.mode.wall": "Wall",
		"button.mode.door": "Door",
		"button.mode.floor": "Floor",
		"button.mode.erase": "Erase",
		"button.mode.office": "Office",
		"button.mode.bathroom": "Bathroom",
		"button.mode.storage": "Storage",
		"button.mode.shop": "Shop",
		"button.mode.recording_booth": "Recording Booth",
		"button.mode.clear_area": "Clear Area",
		"button.mode.chair": "Chair",
		"button.mode.table": "Table",
		"button.mode.wall_pad": "Wall Pad",
		"button.mode.shelf": "Shelf",
		"button.mode.droppoint": "Drop Point",
		"button.mode.checkout": "Checkout",
		"button.talent.assign_booth": "Work here",
		"button.talent.unassign_booth": "Stop working here",
		"button.shop.link_storage": "Link with storage",
		"button.shop.unlink_storage": "Unlink storage",
		"mode.none": "Selection",
		"mode.wall": "Placing walls",
		"mode.door": "Placing doors",
		"mode.floor": "Placing floors",
		"mode.erase": "Removing tiles",
		"mode.designate_office": "Designating office",
		"mode.designate_bathroom": "Designating bathroom",
		"mode.designate_storage": "Designating storage",
		"mode.designate_shop": "Designating shop",
		"mode.designate_recording_booth": "Designating recording booth",
		"mode.clear_area": "Clearing area designation",
		"mode.chair": "Placing chair",
		"mode.table": "Placing table",
		"mode.wall_pad": "Placing wall pad",
		"mode.shelf": "Placing shelf",
		"mode.droppoint": "Placing drop point",
		"mode.checkout": "Placing checkout",
		"designation.office": "Office",
		"designation.bathroom": "Bathroom",
		"designation.storage": "Storage",
		"designation.shop": "Shop",
		"designation.recording_booth": "Recording Booth",
		"role.researcher": "Researcher",
		"role.janitor": "Janitor",
		"role.builder": "Constructor",
		"role.staff": "Staff",
		"role.cashier": "Cashier",
		"role.talent": "Talent",
		"stat.research": "Research",
		"stat.build": "Build",
		"stat.clean": "Clean",
		"recruit.info": "Choose a role, then pick one of three candidates.",
		"recruit.candidate": "{name} | {role} | Res {research} | Build {build} | Clean {clean} | Salary ${salary}",
		"talent.info": "Pick one of three talents, then select one and right click a recording booth.",
		"finance.today_income": "Today income",
		"finance.today_expenses": "Today expenses",
		"finance.today_net": "Today net",
		"finance.month_income": "Month income",
		"finance.month_expenses": "Month expenses",
		"finance.month_net": "Month net",
		"finance.lifetime_income": "Lifetime income",
		"finance.lifetime_expenses": "Lifetime expenses",
		"finance.lifetime_net": "Lifetime net",
		"finance.recording_income": "Recording studio income",
		"finance.shop_sales": "Shop sales income",
		"finance.last_payroll": "Last payroll",
		"finance.monthly_payroll_due": "Monthly payroll due",
		"finance.active_talents": "Active talents",
		"blueprint.wall": "Wall blueprint",
		"blueprint.floor": "Floor blueprint",
		"blueprint.door": "Door blueprint",
		"blueprint.chair": "Chair blueprint",
		"blueprint.table": "Table blueprint",
		"blueprint.wall_pad": "Wall pad blueprint",
		"blueprint.shelf": "Shelf blueprint",
		"blueprint.droppoint": "Drop point blueprint",
		"blueprint.checkout": "Checkout blueprint",
		"research.none": "No active research",
		"research.chairs.name": "Basic Seating",
		"research.chairs.desc": "Unlock office chairs. Assigned chairs boost one worker's research output by 10%.",
		"research.completed": "Completed",
		"log.blueprint_created": "{name} planned at ({x}, {y}).",
		"log.invalid_designation_room": "Area must be inside an enclosed room.",
	},
}


func set_locale(locale_code: String) -> void:
	if TRANSLATIONS.has(locale_code):
		current_locale = locale_code


func translate_key(key: String, replacements: Dictionary = {}) -> String:
	var locale_table: Dictionary = TRANSLATIONS.get(current_locale, TRANSLATIONS["en"])
	var template: String = str(locale_table.get(key, TRANSLATIONS["en"].get(key, key)))
	for replacement_key in replacements.keys():
		template = template.replace("{%s}" % replacement_key, str(replacements[replacement_key]))
	return template
